"""
scripts/action_agent/tools.py

Tools for the Action Agent (merged Agent 4 + Agent 5 of the NPS pipeline).

Two tools only, mirroring decision_action_agent's structure exactly:
  1. notify_manager — Gmail email to the manager with an account-risk
     rollup + recommended actions.
  2. message_rep    — Gmail email to the account owner (rep/CSM/AE) with
     proactive interventions, renewal & upsell alerts, service
     improvement insights, and product gap analysis — all in ONE email

rep_email and manager_email are pulled from session state by the prompt
layer — never invented by the model. This file has no session-state
access itself, same separation of concerns as decision_action_agent.
"""

import base64
from email.mime.text import MIMEText

from google.adk.tools import FunctionTool, ToolContext

from auth.auth import build_gmail_service


def _build_mime_email(to: str, subject: str, body_html: str) -> str:
    """Encode a MIME HTML email as a base64url string for the Gmail API."""
    msg = MIMEText(body_html, "html")
    msg["to"] = to
    msg["subject"] = subject
    return base64.urlsafe_b64encode(msg.as_bytes()).decode()


# ---------------------------------------------------------------------
# TOOL 1 — Notify manager (Gmail API)
# ---------------------------------------------------------------------

async def notify_manager(
    manager_email: str,
    reps_detractor_summary: str,
    tool_context: ToolContext,
) -> dict:
    """Send ONE consolidated email to the manager covering ALL reps'
    Detractor accounts across the whole batch.

    reps_detractor_summary must be pre-formatted by the prompt layer as:
      - One section per rep who has at least one Detractor account,
        headed by that rep's name.
      - Under each rep's name, one block per Detractor account with a
        "Risk Summary" (4 numbered points) and "Recommended Actions"
        (4 numbered points), matching the existing per-account format.

    manager_email MUST come from session state — never invented or guessed.
    """
    subject = "Detractor Account Risk Briefing — All Reps"

    body_html = f"""
    <html><body style="font-family: Arial, sans-serif; line-height: 1.6;">
    <h2 style="color: #c0392b;">Detractor Account Risk Briefing</h2>

    {reps_detractor_summary.replace(chr(10), "<br>")}

    <hr>
    <p style="color: #7f8c8d; font-size: 12px;">
      Generated by the NPS Improvement Agent pipeline.
      Data sourced from ChurnZero, Salesforce, and Gong.
    </p>
    </body></html>
    """

    try:
        service = build_gmail_service()
        raw = _build_mime_email(manager_email, subject, body_html)
        sent = service.users().messages().send(userId="me", body={"raw": raw}).execute()

        return {
            "status": "SENT",
            "type": "notify_manager",
            "manager_email": manager_email,
            "subject": subject,
            "message_id": sent.get("id"),
        }

    except Exception as e:
        return {
            "status": "ERROR",
            "type": "notify_manager",
            "manager_email": manager_email,
            "error_message": str(e),
        }


# ---------------------------------------------------------------------
# TOOL 2 — Message rep / account owner (Gmail API)
# ---------------------------------------------------------------------

async def message_rep(
    rep_id: str,
    rep_name: str,
    rep_email: str,
    accounts_summary: str,
    tool_context: ToolContext,
) -> dict:
    """Send ONE consolidated email to a rep covering ALL of their
    High/Upsell accounts.

    accounts_summary must be pre-formatted by the prompt layer as one
    block per account, each with the same four sections, in this order:
      1. Proactive Interventions
      2. Renewal & Upsell Alerts
      3. Service Improvement Insights (customer-facing talking points)
      4. Product Gap Analysis (objection-handling ammo)

    rep_email MUST come from account_context — never invented or guessed.
    """
    subject = "Action Needed — Your Accounts This Week"

    body_html = f"""
    <html><body style="font-family: Arial, sans-serif; line-height: 1.6;">
    <p>Hi {rep_name},</p>

    <p>Here's a consolidated action summary across your accounts that
    need attention this week:</p>

    <div style="background: #f9f9f9; border-left: 4px solid #2980b9; padding: 12px 16px; margin: 16px 0;">
      {accounts_summary.replace(chr(10), "<br>")}
    </div>

    <p>Please action these items this week to keep these accounts on track.</p>

    <p>Best,<br>Customer Success Ops</p>

    <hr>
    <p style="color: #7f8c8d; font-size: 12px;">
      Generated by the NPS Improvement Agent pipeline.
    </p>
    </body></html>
    """

    try:
        service = build_gmail_service()
        raw = _build_mime_email(rep_email, subject, body_html)
        sent = service.users().messages().send(userId="me", body={"raw": raw}).execute()

        return {
            "status": "SENT",
            "type": "message_rep",
            "rep_id": rep_id,
            "rep_name": rep_name,
            "rep_email": rep_email,
            "subject": subject,
            "message_id": sent.get("id"),
        }

    except Exception as e:
        return {
            "status": "ERROR",
            "type": "message_rep",
            "rep_id": rep_id,
            "rep_name": rep_name,
            "error_message": str(e),
        }


# ---------------------------------------------------------------------
# FunctionTool wrappers
# ---------------------------------------------------------------------

notify_manager_tool = FunctionTool(func=notify_manager)
message_rep_tool = FunctionTool(func=message_rep)
