"""
scripts/action_agent/tools.py

Tools for the Action Agent (merged Agent 4 + Agent 5 of the NPS pipeline).

Two tools only, mirroring decision_action_agent's structure exactly:
  1. notify_manager — Gmail email to the manager with an account-risk
     rollup + recommended actions.
  2. message_rep    — Gmail email to the account owner (rep/CSM/AE) with
     proactive interventions, renewal & upsell alerts, service
     improvement insights, and product gap analysis — all in ONE email

rep_email and manager_email are pulled from session state by the prompt
layer — never invented by the model. This file has no session-state
access itself, same separation of concerns as decision_action_agent.
"""

import base64
from email.mime.text import MIMEText

from google.adk.tools import FunctionTool, ToolContext

from auth.auth import build_gmail_service


def _build_mime_email(to: str, subject: str, body_html: str) -> str:
    """Encode a MIME HTML email as a base64url string for the Gmail API."""
    msg = MIMEText(body_html, "html")
    msg["to"] = to
    msg["subject"] = subject
    return base64.urlsafe_b64encode(msg.as_bytes()).decode()


# ---------------------------------------------------------------------
# TOOL 1 — Notify manager (Gmail API)
# ---------------------------------------------------------------------

async def notify_manager(
    account_id: str,
    account_name: str,
    manager_email: str,
    risk_summary: str,
    recommended_actions: str,
    tool_context: ToolContext,
) -> dict:
    """Send a risk/action briefing email to the manager for this account.

    risk_summary must contain ALL FOUR categories, pre-formatted by the
    prompt layer, at OVERSIGHT/ROLLUP level (not per-deal tactical detail
    — that level of detail belongs in message_rep instead):
      1. Proactive Interventions — which accounts have interventions in
         flight, and flag any that are stuck or overdue.
      2. Renewal & Upsell Alerts — pipeline-level view of renewal risk /
         upsell opportunity across the rep's book of accounts.
      3. Service Improvement Insights — pattern-level signal (e.g. "N
         accounts cite the same friction point"), not a single account's
         raw complaint text.
      4. Product Gap Analysis — aggregated signal worth escalating to
         Product, not a one-off mention tied to a single account.

    recommended_actions must be the manager-level action list derived
    from the four categories above (e.g. coaching actions, escalations,
    resourcing decisions) — distinct from the rep's own tactical actions.

    manager_email MUST come from session state — never invented or guessed.
    """
    subject = f"Account Risk Alert — {account_name} ({account_id})"

    body_html = f"""
    <html><body style="font-family: Arial, sans-serif; line-height: 1.6;">
    <h2 style="color: #c0392b;">Account Risk Briefing: {account_name}</h2>
    <p><b>Account ID:</b> {account_id}</p>

    <h3>Risk Summary</h3>
    <p>{risk_summary.replace(chr(10), "<br>")}</p>

    <h3>Recommended Actions</h3>
    <p>{recommended_actions.replace(chr(10), "<br>")}</p>

    <hr>
    <p style="color: #7f8c8d; font-size: 12px;">
      Generated by the NPS Improvement Agent pipeline.
      Data sourced from ChurnZero, Salesforce, and Gong.
    </p>
    </body></html>
    """

    try:
        service = build_gmail_service()
        raw = _build_mime_email(manager_email, subject, body_html)
        sent = service.users().messages().send(userId="me", body={"raw": raw}).execute()

        return {
            "status": "SENT",
            "type": "notify_manager",
            "account_id": account_id,
            "account_name": account_name,
            "manager_email": manager_email,
            "subject": subject,
            "message_id": sent.get("id"),
        }

    except Exception as e:
        return {
            "status": "ERROR",
            "type": "notify_manager",
            "account_id": account_id,
            "account_name": account_name,
            "error_message": str(e),
        }


# ---------------------------------------------------------------------
# TOOL 2 — Message rep / account owner (Gmail API)
# ---------------------------------------------------------------------

async def message_rep(
    account_id: str,
    account_name: str,
    rep_email: str,
    action_summary: str,
    tool_context: ToolContext,
) -> dict:
    """Send ONE consolidated action email to the rep/CSM/AE who owns
    this account.

    action_summary must contain ALL FOUR sections, pre-formatted by the
    prompt layer, in this order:
      1. Proactive Interventions
      2. Renewal & Upsell Alerts
      3. Service Improvement Insights (reframed as customer-facing
         talking points, not raw internal data)
      4. Product Gap Analysis (reframed as objection-handling ammo for
         the rep's next customer conversation)

    rep_email MUST come from session state — never invented or guessed.
    """
    subject = f"Action Needed — {account_name}"

    body_html = f"""
    <html><body style="font-family: Arial, sans-serif; line-height: 1.6;">
    <p>Hi,</p>

    <p>Here's a consolidated action summary for <b>{account_name}</b>
    that needs your attention this week:</p>

    <div style="background: #f9f9f9; border-left: 4px solid #2980b9; padding: 12px 16px; margin: 16px 0;">
      {action_summary.replace(chr(10), "<br>")}
    </div>

    <p>Please action these items this week to keep the account on track.</p>

    <p>Best,<br>Customer Success Ops</p>

    <hr>
    <p style="color: #7f8c8d; font-size: 12px;">
      Generated by the NPS Improvement Agent pipeline.
    </p>
    </body></html>
    """

    try:
        service = build_gmail_service()
        raw = _build_mime_email(rep_email, subject, body_html)
        sent = service.users().messages().send(userId="me", body={"raw": raw}).execute()

        return {
            "status": "SENT",
            "type": "message_rep",
            "account_id": account_id,
            "account_name": account_name,
            "rep_email": rep_email,
            "subject": subject,
            "message_id": sent.get("id"),
        }

    except Exception as e:
        return {
            "status": "ERROR",
            "type": "message_rep",
            "account_id": account_id,
            "account_name": account_name,
            "error_message": str(e),
        }


# ---------------------------------------------------------------------
# FunctionTool wrappers
# ---------------------------------------------------------------------

notify_manager_tool = FunctionTool(func=notify_manager)
message_rep_tool = FunctionTool(func=message_rep)
